# Generated by Django 4.0.5 on 2022-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('Address', models.TextField()),
                ('Age', models.IntegerField()),
                ('Emailid', models.EmailField(max_length=254)),
                ('JoiningDate', models.DateField()),
                ('Qualification', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Mobileno', models.IntegerField()),
            ],
        ),
    ]
